[project]
name = "address-books-parser-codeberg"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "apache-airflow>=3.0.2",
    "dacite>=1.9.2",
    "pre-commit>=4.2.0",
]
